title: "tks lab"

locale                   : "ja-JP"
lang: "ja-JP"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false



plugins:
  - github-pages
  - jekyll-coffeescript
  - jekyll-include-cache
  - jekyll-titles-from-headings

sass:
  sass_dir: _sass
  style: compressed

remote_theme: "mmistakes/minimal-mistakes@4.22.0"

minimal_mistakes_skin: "contrast"

atom_feed:
  hide: true

defaults:
  # _posts
  - values:
      layout: single
      classes: wide
      toc: true


footer_scripts:
  - "https://code.jquery.com/jquery-3.5.1.min.js"
  - "/assets/js/jquery-my-setting.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.2.2/anchor.min.js"
  - "/assets/js/anchor-my-setting.js"


titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
