title: tks lab

lang: ja-JP

# Build settings
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
highlighter: rouge

plugins:
  - github-pages
  - jekyll-coffeescript

toc:
  min_level: 2 # default: 1
