title: "tks lab"

locale                   : "ja-JP"
lang: "ja-JP"

# Build settings
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
   toc_levels: "1..6"
   
highlighter: "rouge"

plugins:
  - github-pages
  - jekyll-coffeescript
  - jekyll-include-cache

sass:
  sass_dir: _sass
  style: compressed

remote_theme: "mmistakes/minimal-mistakes@4.22.0"

minimal_mistakes_skin: "contrast"

atom_feed:
  hide: true

search: true

head_scripts:
  - /assets/js/lunr-languages/lunr.stemmer.support.js
  - /assets/js/lunr-languages/tinyseg.js
  - /assets/js/lunr-languages/lunr.jp.js
  - /assets/js/lunr-languages/my-setting.js
