title: tks lab

remote_theme:  vsoch/mkdocs-jekyll

lang: ja-JP

# Build settings
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
   toc_levels: "3..6"
   
highlighter: rouge

plugins:
  - github-pages
  - jekyll-coffeescript
