title: tks lab

lang: ja-JP

# Build settings
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
   toc_levels: "3..6"
   
highlighter: rouge

plugins:
  - github-pages
  - jekyll-coffeescript

sass:
  sass_dir: _sass
  style: compressed
